- .aws/task-definition.json
- .github/workflows/ci-cd-workflow.yml
- README.md
- build.gradle
- settings.gradle
- src/main/java/uk/nhs/hee/tis/revalidation/integration/RevalidationIntegrationApplication.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/config/SentryConfiguration.java
- src/main/resources/application.yml
- src/test/java/uk/nhs/hee/tis/revalidation/integration/RevalidationIntegrationApplicationTest.java
Follow the TODOs to update the values provided by the template, several
steps haven't been followed yet so have been left as TODOs or in the
README as a TODO section.
TISNEW-4785
> chore: Update template values for new project

- README.md
- build.gradle
Set up Sonarcloud, Sentry and Dependabot tools, update README and
build.gradle to reflect work done.
TISNEW-4785
> chore: Set up external tools

- .aws/task-definition.json
- README.md
> chore: remove unused secrets from task definition

- build.gradle
> chore: Add Camel dependency

- .aws/task-definition.json
> fix: Move secrets to correct place in task def

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/RecommendationServiceRouter.java
> fix: /api/v1/doctors endpoint should be bridged

- build.gradle
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/api/V1ApiRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/RecommendationServiceRouter.java
> feat: Add assign admin endpoint

- build.gradle
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/api/V1ApiRouter.java
> fix: Swap GET and POST on V1 doctors endpoints

- build.gradle
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/api/ConcernsApiRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ConcernServiceRouter.java
> fix: pass param for concerns endpoint

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/api/CommonUploadApiRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/CommonUploadServiceRouter.java
> chore: add delete document endpoint

- README.md
> docs: Add Router information to README

- build.gradle
- src/main/java/uk/nhs/hee/tis/revalidation/integration/RevalidationIntegrationApplication.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/DoctorConnectionAggregationStrategy.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/api/CommonUploadApiRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/api/ConnectionApiRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/api/V1ApiRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/ConnectionRecordDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/ConnectionSummaryDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/TraineeInfoDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/TraineeSummaryDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/mapper/TraineeConnectionMapper.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/processor/GmcIdProcessorBean.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/CommonUploadServiceRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ConcernServiceRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ConnectionServiceRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/GmcClientServiceRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/RecommendationServiceRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ReferenceServiceRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/TcsServiceRouter.java
> feat: add connection endpoint

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/CommonUploadServiceRouter.java
> fix: remove unmarshal to fix download endpoint

- build.gradle
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/api/ConcernsApiRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ConcernServiceRouter.java
Add /concern/api/concerns/admins endpoint routing.
TISNEW-4972
> feat: Add endpoint for concern admin retrieval

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/DoctorConnectionAggregationStrategy.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/api/ReferenceApiRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/ConnectionInfoDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/ConnectionRecordDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/ConnectionSummaryDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/TraineeInfoDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/TraineeSummaryDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/mapper/ConnectionSummaryMapper.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/mapper/TraineeConnectionMapper.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/processor/GmcIdProcessorBean.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ReferenceServiceRouter.java
> chore: Add missing copyright notices

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/processor/KeycloakBean.java
> chore: set up Keycloak Authenication

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/api/ReferenceApiRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ReferenceServiceRouter.java
> chore: add reference/grades endpoint

- .aws/task-definition.json
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/api/AdminApiRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/api/ConcernsApiRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ConcernServiceRouter.java
- src/main/resources/application.yml
Add the /admins endpoint for the revalidation core service.
TISNEW-4972
> feat: Add /admins endpoint

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/AggregationKey.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ConcernServiceRouter.java
> chore: add employer to concerns/${gmcId} endpoint

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/AggregationKey.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ConcernServiceRouter.java
> Chore/add reference to concerns/${gmcId} endpoint

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/AggregationKey.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ConcernServiceRouter.java
> chore: add gmcNumber to the body of concerns/${gmcId} endpoint

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ConnectionServiceRouter.java
> chore: pass sorting parameter for connection summary

- src/main/resources/application.yml
Added logging level to get more feedback
> chore: added logging level

- .aws/task-definition.json
- build.gradle
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ProfileServiceRouter.java
- src/main/resources/application.yml
Admin details such as assigned roles and DBCs are required, the new
endpoint will return these values as well as others.
TISNEW-5344
> feat: Add endpoint for getting admin details

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ProfileServiceRouter.java
> fix: Remove token url param

- src/main/resources/application.yml
> fix: remove Keycloak Secret

- .aws/task-definition.json
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/helper/Constants.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/processor/RoleNameBean.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ProfileServiceRouter.java
- src/main/resources/application.yml
> feat: added the endpoint for pulling reval admin from profile

- build.gradle
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/api/EnvironmentApiRouter.java
> feat: Add core service's environment endpoint

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/TraineeRecommendationDto.java
> fix: added the missing gmc submission date field

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/api/ConnectionApiRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ConnectionServiceRouter.java
- src/main/resources/application.yml
- connections/add
- connections/remove
TISNEW-4272
> chore: add connection endpoints

- .aws/task-definition.json
> chore: add connection host and port

- .aws/task-definition-prod.json
> chore: add connection endpoint to Prod

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/DoctorRecommendationSummaryAggregationStrategy.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/RecommendationTcsAggregationStrategy.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/RecommendationInfoDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/RecommendationTcsDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/mapper/RecommendationOutcomeMapper.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/RecommendationServiceRouter.java
> chore: doctor and recommendation aggregation to add gmc outcome

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/AggregationKey.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/api/ConnectionApiRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ConnectionServiceRouter.java
> chore: add connection history endpoint

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/AggregationKey.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ConnectionServiceRouter.java
- change aggregation keys
- remove reference dbcs from endpoint
TISNEW-5793
> chore: update connectionDetails endpoint

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/api/ReferenceApiRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ConnectionServiceRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ReferenceServiceRouter.java
> chore: add dbcs reference endpoint

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/api/ConnectionApiRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ConnectionServiceRouter.java
> feat: added connection hide action end point

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/api/ConnectionApiRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/processor/GmcIdProcessorBean.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ConnectionServiceRouter.java
> chore: Hidden connection

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/api/ConnectionApiRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ConnectionServiceRouter.java
> chore: add unhide connections endpoint

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/ConnectionHiddenAggregationStrategy.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/TraineeInfoDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/mapper/TraineeConnectionMapper.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ConnectionServiceRouter.java
> fix: set connectionStatus according to existence of dbc

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ConnectionServiceRouter.java
The connection service router is a bit messy now. Just to add comments and tidy up the code to make it easier to trace.
<NO-TICKET>
> Add comments and tidy up code - connection

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/ConnectionExceptionAggregationStrategy.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/ConnectionHiddenAggregationStrategy.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/ConnectionInfoDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/ConnectionRecordDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/ConnectionTcsRecordDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/mapper/TraineeConnectionMapper.java
- exception
- hidden
- all (all / connected / disconnected) tab
TIS21-1071
> fix: add tcsDesignatedBody to connection summary endpoints

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ConnectionServiceRouter.java
> feat: route exception summary to new exception ES endpoint

- build.gradle
> fix: attempt to fix date format issue

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/api/ConnectionApiRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ConnectionServiceRouter.java
> feat: route endpoint for Connected and Disconnected summary page

- src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListenerTest.java
The listener test should perform the assertions on the build master view
instead of the provided DoctorsForDB object (which will always pass).
TIS21-1264
> test: Refactor listener test to verify master view

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/mapper/MasterDoctorViewMapper.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListener.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/repository/MasterDoctorElasticSearchRepository.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchService.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/view/MasterDoctorView.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListenerTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchServiceTest.java
This is a PR which was raised earlier as draft PR and we worked on it accordingly.
> Feat subscribe sqs gmc doctors tis doctors jay test

- src/main/resources/application.yml
(attempt to fix problem rabbit connection program on stage/prod which keeps generating error log)
> fix: rabbit param name not match

- .aws/task-definition.json
> chore: update Task Role Arn

- .aws/task-definition-prod.json
- .aws/task-definition.json
- src/main/resources/application.yml
> chore: update SQS queue param

- src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListener.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/TraineeDataMessageListener.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchService.java
> fix: add trainee count log from sync

- src/main/java/uk/nhs/hee/tis/revalidation/integration/enums/Status.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/DeferralReasonDto.java
> feat: add status field to deferral reason dto

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/RecommendationTcsAggregationStrategy.java
> fix: handle search recommendation not found

- .aws/task-definition-prod.json
- .aws/task-definition.json
- src/main/resources/application.yml
> fix set RevalApprover, RevalAdmin, RVOfficer for allocate admin list

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/DoctorRecommendationAggregationStrategy.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/DoctorRecommendationSummaryAggregationStrategy.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/DoctorRecommendationAggregationStrategyTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/DoctorRecommendationSummaryAggregationStrategyTest.java
Add unit tests and refactor the doctor recommendation aggregation
strategies.
NO-TICKET
> refactor: add tests and refactor aggregators

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/DoctorRecommendationAggregationStrategy.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/RecommendationInfoDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/RecommendationTcsDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/TraineeCoreDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/TraineeDetailsDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/TraineeRecommendationDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/mapper/RecommendationOutcomeMapper.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/DoctorRecommendationAggregationStrategyTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/DoctorRecommendationSummaryAggregationStrategyTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/RecommendationTcsAggregationStrategyTest.java
> refactor: rename cct date to curriculum end date

- build.gradle
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/ConnectionInfoDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/mapper/TraineeConnectionMapper.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/TraineeDataMessageListener.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/TraineeDataMessageListenerTest.java
TIS21-2669: Filter Recommendations with ES - Rebuild ES Job
> fix: handle curriculum end date from ES rebuild (TCS) sync

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/mapper/MasterDoctorViewMapper.java
TIS21-2669: Filter Recommendations with ES - Rebuild ES Job
> fix: remove incorrect mapper ignore for MasterDoctorViewMapper

- src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/publisher/CdcMessagePublisher.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/publisher/rabbit/RabbitCdcMessagePublisher.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcDoctorService.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcRecommendationService.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcService.java
- src/main/resources/application.yml
- src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/publisher/RabbitCdcMessagePublisherTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/service/CdcDoctorServiceTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/service/CdcRecommendationServiceTest.java
TIS21-2674: [Filter Recommendations with ES] - Event Handling Job For Data Changes (e.g. save draft)
> feat: publish cdc es changes to other services

- src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/service/CdcTraineeUpdateServiceTest.java
TIS21-2748: update master index from changes in Reccomendation Svc
> test: increase code coverage

- src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/listener/CdcRabbitMessageListener.java
TIS21-2873: Update ElasticSearch from TIS
> fix: use the existing app property

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/DoctorRecommendationSummaryAggregationStrategy.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/mapper/TraineeRecommendationMapper.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/RecommendationServiceRouter.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/DoctorRecommendationSummaryAggregationStrategyTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/RecommendationTcsAggregationStrategyTest.java
This reverts commit ce02f5c6.
There are additional fields to be mapped before this can be merged.
The suggested recommendation service response does not include all
required fields. CBA today.
> Revert "refactor: remove unneeded TCS aggregation"

- src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListener.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchService.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchServiceTest.java
Also resolving code smells and improving test coverage
TIS-SHED: Learning about the codebase
> refactor: several standardisations

- src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcRecommendationService.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/testutil/CdcTestDataGenerator.java
> fix: set gmc outcome value to master doctor view

- src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcRecommendationService.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/service/CdcRecommendationServiceTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/testutil/CdcTestDataGenerator.java
TIS-21-3212: Gmc Status/Outcome not showing up for some doctors
> fix: handle null outcomes in recommendation CDC

- .aws/task-definition-prod.json
- .aws/task-definition.json
- src/main/resources/application.yml
> chore: add stage rabbit secrets

- gradle/wrapper/gradle-wrapper.properties
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/api/V1ApiRouter.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/RecommendationServiceRouter.java
TIS21-3511: Route new endpoint through integration service
> feat: add routing for autocomplete endpoint

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/RecommendationServiceRouter.java
> fix: remove json unmarshalling step in autocomplete results

- .aws/task-definition-prod.json
- .aws/task-definition.json
- src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListener.java
- src/main/resources/application.yml
TIS21-3775: Remove legacy steps 6 and 7 from code and rabbit config
[TIS21-3775]: https://hee-tis.atlassian.net/browse/TIS21-3775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: remove extremely inefficient getMaster ES sync setup

- src/main/java/uk/nhs/hee/tis/revalidation/integration/config/EsRestClientConfig.java
If this works, I will terraform the port.
TIS21-3416
> chore:use SSL for ES

- src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListener.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListenerTest.java
Reverts Health-Education-England/tis-revalidation-integration#385
> Revert "fix:extend visibility timeout For resync indices"

- src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/helper/ElasticsearchIndexHelper.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchService.java
> feat:use filtered alias

- src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/dto/ConnectionInfoDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/ConnectionInfoDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/mapper/TraineeConnectionMapper.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListener.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/view/MasterDoctorView.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/service/CdcTraineeUpdateServiceTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/testutil/CdcTestDataGenerator.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/router/mapper/MasterDoctorViewMapperTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListenerTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/TraineeDataMessageListenerTest.java
TIS21-4194: TCS, Integration Service & Connection Service - Remove field connectionStatus
> chore: remove unused field connectionStatus

- src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/view/MasterDoctorView.java
TIS21-4554: Should ignore case when searching for doctors in Connections summary
> fix: add fieldata=true mapping for wildcard fields

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/processor/TraineeDetailProcessor.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/TraineeServiceRouter.java
> fix:TraineeServiceRouter

- src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ConnectionServiceRouter.java
> fix: remove unecessary call to tcs endpoint for get connection history

- src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/listener/CdcRabbitMessageListener.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcTraineeUpdateService.java
- src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/repository/MasterDoctorElasticSearchRepository.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/listener/CdcRabbitMessageListenerTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/service/CdcTraineeUpdateServiceTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcDoctorServiceTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcRecommendationServiceTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcTraineeUpdateServiceTest.java
depends on https://github.com/Health-Education-England/TIS-TCS/pull/981
TIS21-5100
> feat:handle gmcNumber from reliable to unreliable

- src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchService.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchServiceTest.java
TIS21-4360: Revalidation Connections: GET Discrepancies where TISDBC != GMCDBC
> feat: add discrepancies alias and filter to masterdoctorindex

- src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchService.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchServiceTest.java
Reverts Health-Education-England/tis-revalidation-integration#402
> Revert "feat: add discrepancies alias and filter to masterdoctorindex"

- build.gradle
- src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchService.java
- src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchServiceTest.java
Just replicated Cai's work. 
TIS21-7168
> feat: add alias to discrepancies elastic search

- build.gradle
- src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchService.java
discrepancies filter is fixed based on java 17's multi string feature
TIS21-7168
> fix: fix discrepancies filter string
