Health-Education-England/tis-revalidation-integration

.aws/task-definition.json
README.md

Add `SENTRY_DSN` and `SENTRY_ENVIRONMENT` to the task definition file so
that exceptions are able to be sent to the Sentry project.
TISNEW-4890

feat: Add Sentry DSN and Environment variables

---

.aws/task-definition.json

The `SENTRY_ENVIRONMENT` variable was placed in to the `secrets` array,
when it should be in the `environment` array.
TISNEW-4890

fix: Move `SENTRY_ENVIRONMENT` to correct location

---

build.gradle
src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ProfileServiceRouter.java

The keycloak token is required when making a request to the TIS profile
service.
TISNEW-5344

fix: Add keycloak token to profile request

---

build.gradle
src/main/java/uk/nhs/hee/tis/revalidation/integration/router/processor/UsernameBean.java
src/test/java/uk/nhs/hee/tis/revalidation/integration/router/processor/UsernameBeanTest.java

Currently the details of the machine user are returned instead of the
details of the logged in user, change the endpoint used when requesting
the admin profile to get one that can get by username instead of from
the current token.
TISNEW-5344

fix: Return current user's details

---

src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ConnectionServiceRouter.java

Pagination was not working because the "pageNumber" parameter was not propagated from the integration layer to the TCS service as it was not explicitly parameterised.
TIS21-947

fix: pagination for the hidden connection tab

---

src/main/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/ConnectionHiddenAggregationStrategy.java

The previous fix did not cover the logic for the connection status field. This is to add connection status logic in the route when hidden connection is null.
TIS21-109

fix: add connection status in null hidden connection route

---

src/main/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/TraineeNotesAggregationStrategy.java
src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/TraineeDetailsDto.java
src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/TraineeNotesDto.java
src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/TraineeNotesInfoDto.java
src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/TraineeServiceRouter.java

Trainee Notes data are added to trainee details endpoint `/api/trainee/{gmcId}/`.
It would be called by left side component of all details page (recommendations / concerns / connections) for the trainee information)
TIS21-86

feat: view trainee notes

---

src/main/java/uk/nhs/hee/tis/revalidation/integration/entity/RevalidationSummaryDto.java
src/main/java/uk/nhs/hee/tis/revalidation/integration/router/dto/RevalidationSummaryDto.java
src/main/java/uk/nhs/hee/tis/revalidation/integration/router/message/payload/IndexSyncMessage.java
src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListener.java
src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/view/MasterDoctorView.java
src/main/resources/application.yml
src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListenerTest.java

TIS21-2669
The additional fields which are needed to make the revalidation summary page for elastic search index is added in this PR. The fields are being received from the sqs queue.

feat: added revalidation fields to master index

---

src/main/java/uk/nhs/hee/tis/revalidation/integration/router/mapper/MasterDoctorViewMapper.java
src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchService.java
src/test/java/uk/nhs/hee/tis/revalidation/integration/router/mapper/MasterDoctorViewMapperTest.java
src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchServiceTest.java

- swap source and target param passing to the mapper
- add annotation so target field won't be overridden when source is null
TIS21-2669: Filter Recommendations with ES - Rebuild ES Job

fix: update master index mapper

---

src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcTraineeUpdateService.java
src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/service/CdcTraineeUpdateServiceTest.java

Searching for null or empty GMC numbers will return all matches.
The visible problem is logging when there are >10K matches.
There is a bigger problem about updating based on GMC number when TIS ID
doesn't match but that a data quality issue.
TIS21-2675: Filtering by Programme Name

refactor: check ES by TIS ID if GMC is placeholder

---

build.gradle
src/main/java/uk/nhs/hee/tis/revalidation/integration/router/mapper/MasterDoctorViewMapper.java
src/test/java/uk/nhs/hee/tis/revalidation/integration/router/mapper/MasterDoctorViewMapperTest.java

Defatult nullValuePropertyMappingStrategy is `SET_TO_NULL`. 
We've already set the strategy to `IGNORE` on mapper level.
And setting the strategy on bean mapping or field mapping will overwite it.
TIS21-3229

fix:allow some TCS null value update to ES

---

src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListener.java

TIS21-3491: Do an efficient and targeted resync

fix: disable part of es resync job that kills mongoDB

---

src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListener.java
src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListenerTest.java

When verifying the resync operation on Stage, I found the whole process was triggered 3 times by different ECS tasks, as shown below:
After the resync was done, we got 3 recommendationindex on ES:
From the logs, we can see the interval between each task is 30 seconds, which matches the config of visibilityTimout.
To solve this issue, we can extend the visibilityTimeout for this message.
Another option is to use FIFO queue.
Some explanations can be found here: https://stackoverflow.com/questions/30187683/aws-multiple-instances-reading-sqs
TIS21-3416

fix:extend visibility timeout For resync indices

---

src/main/java/uk/nhs/hee/tis/revalidation/integration/router/mapper/MasterDoctorViewMapper.java
src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/view/MasterDoctorView.java
src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/service/CdcDoctorServiceTest.java
src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/service/CdcTraineeUpdateServiceTest.java
src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/testutil/CdcTestDataGenerator.java

TIS21-4510: Connections Discrepnacies Data Cleanup: Remove last- prefix from disconnected DBCs

fix: allow null DBC from revalidation services for disconnected doctors

---

build.gradle
src/main/resources/application.yml

1. update camel to use bom and upgrade to 3.20.5
2. after version upgrade, all rest api didn't work (404) and finally found it was the context-path which needed an update.
TIS21-4548

chore:upgrade Camel

---

build.gradle
src/main/resources/application.yml

- camel.dataformat.jackson.auto-discover-objectj-mapper: true
- delete the duplicate dependency.
TIS21-4548

chore:config for ObjectMapper

---

src/main/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/DoctorRecommendationAggregationStrategy.java
src/main/java/uk/nhs/hee/tis/revalidation/integration/router/processor/GmcIdProcessorBean.java
src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/RecommendationServiceRouter.java
src/test/java/uk/nhs/hee/tis/revalidation/integration/router/aggregation/DoctorRecommendationAggregationStrategyTest.java

Problem to resolve:
For getRecommendationByGmcId endpoint in Recommendation service, when there's no doctor record found in `doctorsForDB` collection, Recommendation service returns a null body. But in the router, `unmarshal` can't handle the null body, so it throws an exception `com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input`, so a 500 will be returned from Camel to the frontend, see: https://stage-revalidation.tis.nhs.uk/recommendation/7560496.
Change:
1. remove marshal from the router, and do deserialisation manually in the aggregator. (It's not possible to add try catch block around a marshal operation).
3. when the message body from Recommendation service is null, return a 404 not found error to frontend.
TIS21-4548

fix:getRecommendationByGmcId

---

.github/workflows/ci-cd-workflow.yml
.github/workflows/pr-analysis.yml
.github/workflows/prod.deploy.yml

Remove the unused ecr and codeartifact user tokens and replace it with a role reference to the `github-actions-deployer-role` accessible using OIDC.
TIS21-4862

build: use OIDC for AWS credentials

---

.github/workflows/ci-cd-workflow.yml

Java 11 is deprecated for analysis and project can be built with 17 too
NO-CARD: Shaving off TIS21-4956 Reval Sync Issues

chore(deps): build on Java 17

---

.github/workflows/prod.deploy.yml

Triggering an ECS deployment circuit breaker can cause a false positive when waiting for service stability.
Add a post-deployment verification step to check the task def ARN against the expectation.
TIS21-4819
TIS21-5332

build: verified deployed task definition

---

src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/RecommendationServiceRouter.java

The ReST service was updated to indent json responses. As well as indents, the "pretty" format has a space after field names.
TIS21-5504: Unscheduled prod updates

fix: update regex returned by the ReST service

---

.github/workflows/ci-cd-workflow.yml
.github/workflows/prod.deploy.yml

Merge was failing because it used a deprecated version of `actions/upload-artifact: v3
TIS21-7168

chore: upgrade github actions verstion to 4

---

.github/workflows/ci-cd-workflow.yml

In workflow V3, if you uploaded an artifact with the same name multiple times, GitHub Actions would just overwrite or merge the content without telling us.
However, in V4 behaviour they made it stricter. Now, if you try to upload an artifact with a name already used in the same workflow run, it throws a 409 Conflict error. So it is required to use unique names in different steps.
TIS21-7168

fix: use unique names in different steps

---

src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/handler/CdcMessageHandler.java
src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/util/CdcDateDeserializer.java
src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/handler/CdcDoctorMessageHandlerTest.java
src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/testutil/CdcTestDataGenerator.java
src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/util/CdcDateDeserializerTest.java

When testing DocumentDB trigger, I found in the cdc event messages, the date format is changed to an object type as "{$date": "2025-04-29T00:00:00Z"}, so made some changes on the deserializer. 
Beside, I tested by updating data in the docDB collection directly and noticed UPDATE operation type is not handled, so added it in.
TIS21-6275

fix: handle date format change
